### ISSUE TITLE
1-click install App + Installation - OS Windows

### ISSUE THREAD

**Issue by SlnPons** [massalabs/Thyra-Menu-Bar-App#12]
**Context** 
To enable everyone to use thyra and interact with the blockchain, Thyra needs to be very easy to install AND to use. 
We now have a 1-click install of: 
* Thyra for Windows: https://github.com/massalabs/thyra/issues/345
* Thyra app with an icon-tray: https://github.com/massalabs/thyra/issues/233
The objective of this task is to combine the installation and the icon tray into one and only 1-click install. 

**User flow** 
1. As a user, when I go to thyra github page, I want to be able to download a .exe file on my computer. 
2. As a user, once I downloaded the .exe file on my computer, I want to click on it to open it and see a screen / pop-up / windows that enable me to know that Thyra has been installed.
3. As a user, once I successfully installed Thyra on my computer, I want to be able see an icon tray on my desktop nav bar that enables me to: start and stop thyra as well as access the existing wallet & websites page.

**How to**

- [ ] Add to the current App script an execution of the installation script for windows
- [ ] Make sure that user can have all this installed in 1-click (ie: as less as possible)

**Technical details** 
To be added by dev

**Comment by SlnPons** [comment]
@B-Naoufal please add some technical details ..... this issue won't be closed if no detail added

**Comment by B-Naoufal** [comment]
@SlnPons done , can you review it please

**Comment by SlnPons** [comment]
Not working properly, see bug: https://github.com/massalabs/Thyra-Menu-Bar-App/issues/25 that needs to be solved

**Comment by SlnPons** [comment]
Hey @0xMazout I saw you testing this install. Are you working on windows? 
If so, when you have time it's not urgent but could you help me to write down the new process for people on windows AND non-dev to install it on their machine please? 

With the new release it changes the process and script but I still haven't updated it as I'm in PLS with windows :/
