### ISSUE TITLE
ThyraMenuAppBar killed doesn't release the port associated

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/Thyra-Menu-Bar-App#26]

**Comment by 0xMazout** [comment]
![Image](https://user-images.githubusercontent.com/10938862/213209695-b844d791-2dca-47a8-a496-99bd24ce343b.png)


5 minutes after killed Thyra menu App bar Socket is not released

**Comment by B-Naoufal** [comment]
To be corrected in https://github.com/massalabs/Thyra-Menu-Bar-App/blob/main/utils/background_process.py : Line : 61,  
`self.process.kill()` kill only the current process : thyra and not the the childs launched from thyra (plugins), you could loop on all childs of the subprocess and kill them (wallet-plugin, ...)

**Comment by SlnPons** [comment]
@B-Naoufal sorry to bother. Was this problem only on Windows? 
Can I test it and if yes, how can I do this?

**Comment by B-Naoufal** [comment]
@SlnPons it was a bug in every os.  
To test it :  
1- Launch thyra-app and start thyra.
2- check that the ports are being associated by running the following commands in a new terminal:  
`lsof -i : 4200`   
`lsof -i : 4201`   
`lsof -i : 4202`   
`lsof -i :80` 
`lsof -i :443` 
The result after runing each command should be not empty.
3- from thyra-app : stop thyra.  
4- run the same commands and now you should have an empty result for each one of them.
